/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ProyeccionesRouteImport } from './routes/proyecciones'
import { Route as OperacionesRouteImport } from './routes/operaciones'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportarRouteImport } from './routes/importar'
import { Route as ImportacionesRouteImport } from './routes/importaciones'
import { Route as DashboardGerencialRouteImport } from './routes/dashboard-gerencial'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperacionesJobIdRouteImport } from './routes/operaciones.$jobId'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyeccionesRoute = ProyeccionesRouteImport.update({
  id: '/proyecciones',
  path: '/proyecciones',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesRoute = OperacionesRouteImport.update({
  id: '/operaciones',
  path: '/operaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarRoute = ImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacionesRoute = ImportacionesRouteImport.update({
  id: '/importaciones',
  path: '/importaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGerencialRoute = DashboardGerencialRouteImport.update({
  id: '/dashboard-gerencial',
  path: '/dashboard-gerencial',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionesJobIdRoute = OperacionesJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => OperacionesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casos': typeof CasosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard-gerencial': typeof DashboardGerencialRoute
  '/importaciones': typeof ImportacionesRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/operaciones': typeof OperacionesRouteWithChildren
  '/proyecciones': typeof ProyeccionesRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/operaciones/$jobId': typeof OperacionesJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casos': typeof CasosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard-gerencial': typeof DashboardGerencialRoute
  '/importaciones': typeof ImportacionesRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/operaciones': typeof OperacionesRouteWithChildren
  '/proyecciones': typeof ProyeccionesRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/operaciones/$jobId': typeof OperacionesJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/casos': typeof CasosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard-gerencial': typeof DashboardGerencialRoute
  '/importaciones': typeof ImportacionesRoute
  '/importar': typeof ImportarRoute
  '/login': typeof LoginRoute
  '/operaciones': typeof OperacionesRouteWithChildren
  '/proyecciones': typeof ProyeccionesRoute
  '/reportes': typeof ReportesRoute
  '/usuarios': typeof UsuariosRoute
  '/operaciones/$jobId': typeof OperacionesJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/casos'
    | '/configuracion'
    | '/dashboard-gerencial'
    | '/importaciones'
    | '/importar'
    | '/login'
    | '/operaciones'
    | '/proyecciones'
    | '/reportes'
    | '/usuarios'
    | '/operaciones/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/casos'
    | '/configuracion'
    | '/dashboard-gerencial'
    | '/importaciones'
    | '/importar'
    | '/login'
    | '/operaciones'
    | '/proyecciones'
    | '/reportes'
    | '/usuarios'
    | '/operaciones/$jobId'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/casos'
    | '/configuracion'
    | '/dashboard-gerencial'
    | '/importaciones'
    | '/importar'
    | '/login'
    | '/operaciones'
    | '/proyecciones'
    | '/reportes'
    | '/usuarios'
    | '/operaciones/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  CasosRoute: typeof CasosRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardGerencialRoute: typeof DashboardGerencialRoute
  ImportacionesRoute: typeof ImportacionesRoute
  ImportarRoute: typeof ImportarRoute
  LoginRoute: typeof LoginRoute
  OperacionesRoute: typeof OperacionesRouteWithChildren
  ProyeccionesRoute: typeof ProyeccionesRoute
  ReportesRoute: typeof ReportesRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyecciones': {
      id: '/proyecciones'
      path: '/proyecciones'
      fullPath: '/proyecciones'
      preLoaderRoute: typeof ProyeccionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones': {
      id: '/operaciones'
      path: '/operaciones'
      fullPath: '/operaciones'
      preLoaderRoute: typeof OperacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar': {
      id: '/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof ImportarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importaciones': {
      id: '/importaciones'
      path: '/importaciones'
      fullPath: '/importaciones'
      preLoaderRoute: typeof ImportacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-gerencial': {
      id: '/dashboard-gerencial'
      path: '/dashboard-gerencial'
      fullPath: '/dashboard-gerencial'
      preLoaderRoute: typeof DashboardGerencialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operaciones/$jobId': {
      id: '/operaciones/$jobId'
      path: '/$jobId'
      fullPath: '/operaciones/$jobId'
      preLoaderRoute: typeof OperacionesJobIdRouteImport
      parentRoute: typeof OperacionesRoute
    }
  }
}

interface OperacionesRouteChildren {
  OperacionesJobIdRoute: typeof OperacionesJobIdRoute
}

const OperacionesRouteChildren: OperacionesRouteChildren = {
  OperacionesJobIdRoute: OperacionesJobIdRoute,
}

const OperacionesRouteWithChildren = OperacionesRoute._addFileChildren(
  OperacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  CasosRoute: CasosRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardGerencialRoute: DashboardGerencialRoute,
  ImportacionesRoute: ImportacionesRoute,
  ImportarRoute: ImportarRoute,
  LoginRoute: LoginRoute,
  OperacionesRoute: OperacionesRouteWithChildren,
  ProyeccionesRoute: ProyeccionesRoute,
  ReportesRoute: ReportesRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
